# Generated by Django 3.0.6 on 2020-05-09 21:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='youtubecredentials',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
