# Generated by Django 3.0.6 on 2020-05-13 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_youtube', '0002_auto_20200509_2142'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='youtubecredentials',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='youtubecredentials',
            name='last_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubecredentials',
            name='quota_restarts_at',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
